name: debianCheck
on: 
  workflow_call:

permissions: write-all

jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: debian-prefix-check
        if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@debian-prefix-check
      - id: debian-version-check
        if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@debian-version-check
      - id: debian-keys-check
        if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@debian-keys-check
      - id: summary-result
        if: always()
        continue-on-error: true
        run: |
          summary-status="是"
          for status in ${preStatus} ${versionStatus} ${keysStatus}
            if [ "$status" == "true" ]; then
              summary-status="否"
            fi
          done
          echo "summary-status=$summary-status" >> $GITHUB_OUTPUT
          rm -rf comment.txt
          echo ${{steps.debian-prefix-check.outputs.check_msg}} | tee -a comment.txt
          echo ${{steps.debian-version-check.outputs.check_msg}} | tee -a comment.txt
          echo ${{steps.debian-keys-check.outputs.check_msg}} | tee -a comment.txt
        env:
          preStatus: ${{ steps.debian-prefix-check.outputs.isFail }}
          versionStatus: ${{ steps.debian-version-check.outputs.isFail }}
          keysStatus: ${{ steps.debian-keys-check.outputs.isFail }}
      - if: always() && steps.summary-result.outputs.summary-status == '否'
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@post-check
        with:
          comment-file: comment.txt
          reviewers: ckux
      - if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@send-data
        with:
          testtype: "debianCheck"
          status: ${{ steps.summary-result.outputs.summary-status }}
          result: ${{ steps.summary-result.outputs.summary-status == '否' && '1' || '0' }}
      - if: always() && steps.summary-result.outputs.summary-status == '否'
        run: exit 1