name: test
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: check1
        run: |
            # echo "summary-status=[${goStatus},${cppStatus},${shellStatus}]" >> $GITHUB_OUTPUT
            echo "summary-status={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        env:
            goStatus: 'false'
            cppStatus: 'true'
            shellStatus: 'false'
      - if: always()
        uses: reviews-team-test/ci-check-action@main
        with:
          status: ${{ fromJSON(steps.check1.outputs.summary-status) }}