name: test
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: check1
        run: |
            echo "summary-status=[${goStatus},${cppStatus},${shellStatus}]" >> $GITHUB_OUTPUT
        env:
            goStatus: 'false'
            cppStatus: 'true'
            shellStatus: 'false'
      - if: always()
        uses: reviews-team-test/ci-check-action@main
        with:
          status: ${{ contains(fromJSON('["push", "pull_request"]'), 'pull') }}